### ISSUE TITLE
[FEAT] 메인 페이지

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/open-market#10]
## Description
설명을 작성하세요.
## Todo
- [x] 탑바 컴포넌트
- [x] 상품 리스트 컴포넌트: 무한 스크롤
- [x] 푸터
- [x] 탭 순서: 탑바 → 푸터 → 상품 리스트
- [ ] 상품 이미지 너비 높이 미리 정해두기
