### ISSUE TITLE
[FEAT] 회원 가입 페이지

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/open-market#12]
## Todo
- [x] 구매, 판매 탭 클릭에 따라 보여지는 HTML 다르게 하기
- [x] 구매 회원 가입
    - [x] 유효성 검사 및 아이디 중복 체크
    - [x] 회원가입 요청 전 인풋 유효 여부 확인
    - [x] 회원가입 요청 및 포커스 아웃시 유효성 검사에서 미처 잡아내지 못한 것과 휴대폰 중복 체크 처리
- [ ] 판매 회원 가입
    - [x] 유효성 검사(사업자 등록번호, 스토어 이름)
    - [ ] 회원가입 요청 전 인풋 유효 여부 확인 
    - [ ] 회원가입 요청
- [ ] 인풋에 placeholder로 입력 조건 보여주기
- [ ] 회원가입 성공시 로그인 페이지로 이동
