### ISSUE TITLE
[ETC] 웹팩 및 바벨 설정

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/open-market#2]
## Description
개발/빌드를 위한 웹팩과 구형 브라우저 지원을 위한 바벨을 설치 및 설정하고자 함.
## Todo
- [ ] 웹팩 공용
- [ ] 웹팩 dev
    - [ ] SPA 개발 편의성을 위해 webpack-dev-server 이용하기
    - [ ] [style-loader](https://velog.io/@bepyan/VanillaJS-webpack5-MiniCssExtractPlugin#:~:text=css%20%ED%8C%8C%EC%9D%BC%EC%9D%84%20%EC%B6%94%EC%B6%9C%ED%95%B4%EC%A3%BC%EB%8A%94,css%EB%A5%BC%20%EC%95%8C%EC%95%84%EC%84%9C%20link%ED%95%B4%EC%A4%80%EB%8B%A4.)
    - [ ] devtool: inline-source-map
- [ ] 웹팩 prod
    - [ ] [MiniCssExtractPlugin](https://velog.io/@bepyan/VanillaJS-webpack5-MiniCssExtractPlugin#:~:text=css%20%ED%8C%8C%EC%9D%BC%EC%9D%84%20%EC%B6%94%EC%B6%9C%ED%95%B4%EC%A3%BC%EB%8A%94,css%EB%A5%BC%20%EC%95%8C%EC%95%84%EC%84%9C%20link%ED%95%B4%EC%A4%80%EB%8B%A4.)
    - [ ] devtool: source-map
- [ ] 바벨
- [ ] .gitignore
