### ISSUE TITLE
[FEAT] 라우터 기능 및 배포

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/open-market#6]
## Description
라우터 기능을 구현하고 Netlify에 배포해 잘 작동하는지 확인하고자 함
## Todo
- [x] 라우터 기능
    - [x] 상품 리스트(홈): Home.js
    - [x] 로그인: Login.js
    - [x] 회원가입: SignUP.js
    - [x] 장바구니: Cart.js
    - [x] 제품 상세: Detail.js
    - [x] 주문 및 결제: Order.js
    - [x] 판매자 대쉬보드: DashBoard.js
    - [x] 에러: Error.js
- [ ] Netlify 배포 잘 되는지 확인
